const descriptions = [
  "Siempre estoy emocionado de conocer a nuevas personas y hacer amigos.",
  "Soy un perro muy sociable que se lleva bien con otros perros y humanos.",
  "Me encanta jugar y hacer ejercicio con mis amigos humanos y caninos.",
  "Soy un perro que siempre está emocionado por conocer nuevos amigos y me encanta jugar con el agua.",
  "Soy un perro muy leal que siempre está al lado de mis seres queridos.",
  "Siempre estoy dispuesto a hacer nuevos amigos para jugar juntos.",
  "Soy muy amigable con los niños y siempre estoy feliz de jugar con ellos.",
  "Soy un perro muy tranquilo y gentil que nunca mostraría agresividad.",
  "Me encanta acurrucarme y pasar tiempo con mis dueños.",
  "Siempre estoy feliz de dar paseos y explorar el mundo con mi familia.",
  "Soy un perro muy juguetón y siempre estoy dispuesto a compartir mis juguetes.",
  "Siempre estoy dispuesto a hacer nuevos amigos caninos y humanos.",
  "Soy un perro muy amable y me encanta ayudar a mis dueños.",
  "Siempre estoy emocionado de ver a mis seres queridos, incluso si sólo han estado fuera por unos minutos.",
  "Me encanta dar abrazos y besos a mis seres queridos para mostrarles cuánto los quiero.",
  "Soy muy respetuoso con otros animales y siempre me llevo bien con ellos.",
  "Siempre estoy feliz de pasar tiempo al aire libre con mis amigos humanos.",
  "Soy un perro muy enérgico y siempre estoy dispuesto a jugar y correr con mis amigos.",
  "Soy muy protector con mis seres queridos y siempre estoy dispuesto a cuidar de ellos.",
  "Me encanta hacer trucos y mostrarles a todos lo inteligente que soy.",
  "Siempre estoy feliz de hacer nuevos amigos y tengo un gran corazón para todos.",
  "Soy muy amigable con los extraños y siempre estoy dispuesto a darles la bienvenida.",
  "Soy un perro muy feliz que siempre está saltando de alegría.",
  "Siempre estoy dispuesto a compartir mi comida y agua con otros perros.",
  "Soy un perro muy amistoso que siempre está dispuesto a jugar y hacer amigos.",
  "Siempre estoy enfocado en hacer ejercicio y mantenerme en forma.",
  "Soy muy paciente y siempre estoy dispuesto a esperar a mis seres queridos cuando están ocupados.",
  "Me encanta dormir y acompañar a mi familia humana.",
  "Soy un perro muy amable y siempre estoy feliz de recibir caricias y mimos.",
  "Siempre estoy emocionado de salir y explorar nuevos lugares con mi familia."
];

export const getRandomDescription = () => descriptions[Math.floor(Math.random() * descriptions.length)];